server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - "localhost"
    labels:
      job: varlogs
      __path__: /var/log/*log

- job_name: docker
  static_configs:
      targets:
        - "localhost"
      labels:
        job: docker
        __path__: /var/lib/docker/containers/*/*.log

- job_name: docker_json
  static_configs:
    - targets:
        - "localhost"
      labels:
        job: docker_json
        __path__: /var/lib/docker/containers/*/*.log
  pipeline_stages:
    - json:
        expressions:
          output: log
          stream: stream
          time: time
    - labels:
        stream:
    - timestamp:
        source: time
        format: RFC3339Nano
    - output:
        source: output
